UIG-1208 No content message
milieuinfo/webcomponent-vl-ui-rich-data pull request #31
Opened 2021-04-21 10:17 UTC by Rubenth

zie https://github.com/milieuinfo/webcomponent-vl-ui-rich-data-table/issues/60

2021-04-26 15:54 UTC, coemans requested changes
Best demo pagina's samenvoegen en e2e test introduceren om interactie met empty slot toe te voegen.

2021-04-26 15:58 UTC, coemans commented
@Rubenth blijkbaar zit naast de nieuwe feature hier ook de fix voor #29. Als het mogelijk is, liever aparte PR voorzien zodat scope per PR beperkt blijft, reviewen vlotter verloopt en via de release notes beter genavigeerd kan worden naar de context van wijzigingen.

2021-05-04 13:55 UTC, Rubenth commented
- demo pagina's samengevoegd
- e2e test toegevoegd
- niet mogelijk om fix voor #29 te extracten, we lopen tegen issues aan die hiermee gerelateerd zijn.

2021-05-21 10:05 UTC, coemans commented on src/vl-rich-data.js
> +                <slot name="no-content-message"></slot>
Ik hem slot hernoemd van `no-content-message` naar `no-content` aangezien het meer dan een bericht kan zijn en meer de lading dekt.

2021-05-21 10:05 UTC, coemans commented on src/vl-rich-data.js
> +              <div id="no-content-wrapper" is="vl-column" data-vl-size="12" data-vl-medium-size="12" class="vl-u-visually-hidden">
A11Y probleem opgelost.

2021-05-21 10:05 UTC, coemans commented on src/vl-rich-data.js
> +        this.__toggleContent(this._paging);
Argument wordt niet gebruikt.

2021-05-21 10:05 UTC, coemans commented on src/vl-rich-data.js
> +  }
Refactoring uitgevoerd om code minder zwaar te maken. Het sorter element mag ondanks dat er geen resultaten zijn getoond worden.

2021-05-21 10:05 UTC, coemans commented on src/vl-rich-data.js
> +    }
Default voorzien voor wanneer no-content slot element niet bestaat.

2021-05-21 10:05 UTC, coemans commented on test/unit/vl-rich-data.test.html
> +      // Hij is van in het begin al leeg en daarom slaagt de test.
Dit test wel degelijk iets, er was vroeger namelijk een bug dat er undefined getoond werd wanneer de total items van de vl-pager leeg of undefined was. Het is niet omdat initieel de waarde ook 0 is, dat de test niets test.

2021-05-21 10:15 UTC, coemans commented on test/e2e/components/vl-rich-data.js
> +  }
Wrapper code is overbodig. Refactoring uitgevoerd.

2021-05-21 10:39 UTC, coemans commented on demo/vl-rich-data.html
> +      </vl-demo>
Demo is overbodig want wordt niet gebruikt in de e2e testen, voldoende dekking via unit test dat initieel het no-content slot element getoond wordt.

2021-05-21 10:41 UTC, coemans approved these changes

2021-05-21 10:41 UTC, coemans commented on src/vl-rich-data.js
> +    observer.observe(this, {childList: true, subtree: true});
Onduidelijk waarom deze code wijziging werd uitgevoerd. Na een revert faalt er geen test. Indien deze code wijziging wel nodig is, kan dit best blijken uit de testen om regressie te voorkomen. Voorlopig werd de code gereverted.

2021-05-21 10:50 UTC, merged

2021-05-21 10:59 UTC, coemans commented on src/vl-rich-data.js
> +    observer.observe(this, {childList: true, subtree: true});
Zie PR #40.